# Generated by Django 5.0.7 on 2024-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_category', models.CharField(choices=[('admin', 'Apply as Admin'), ('buyer', 'Apply as Buyer')], max_length=10)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('country_of_citizenship', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
